---
output:
  pdf_document:
    latex_engine: pdflatex
    template: svm-latex-cv.tex
geometry: margin=0.8in

title: "CV"
author: "Lachlan Deer"
orcid: "https://orcid.org/0000-0001-8646-6095"
jobtitle: "PhD Candidate, Department of Economics, University of Zurich"
address: "Schoenberggasse 1, Zurich, CH 8001"
fontawesome: yes
email: lachlan.deer@gmail.com
#github: lachlandeer
phone: "+41 787-698-789"
web: 'lachlandeer.github.io'
#updated: no

keywords: RMarkdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 10pt
linkcolor: blue
urlcolor: blue
---

# FORTHCOMING EMPLOYMENT

*Booth School of Business, University of Chicago*, Postdoctoral Fellow. \hfill 08/2019 - 10/2020

# EDUCATION

*University of Zurich*, Ph.D. in Economics. \hfill 2013-07/2019 (exp.)

*University College London*, M.Sc in Economics (with Distinction). \hfill 2013

*University of Adelaide*, M.Phil in Economics. \hfill 2012

*University of Adelaide*, Bachelor's Degree in Economics (with First Class Honours). \hfill 2009

# PROFESSIONAL AFFILIATIONS
CRS Fellow, Centre for Reproducible Science, University of Zurich. \hfill 2019


# RESEARCH INTERESTS

Quantitative Marketing, Digital Marketing, Text as Data, Applied Econometrics, Media Economics.

# RESEARCH PAPERS

## JOB MARKET PAPER

**L. Deer**, P.K. Chintagunta and G.S. Crawford, "[*Online Word of Mouth and the Performance of New Products*](http://lachlandeer.github.io/files/deer_jmp.pdf)."

## WORK IN PROGRESS

**L. Deer**, P.K. Chintagunta and G.S. Crawford, "*How does Advertising Influence Online Word of Mouth? Evidence from Twitter*." ([Slides with preliminary results](http://lachlandeer.github.io/files/ads_wom_slides.pdf))

<!-- **L. Deer**, P.K. Chintagunta and G.S. Crawford, "*What Consumers Tweet About: Evidence from Movie Tweets*" -->

F. Javier Barreda, **L. Deer**, CS. Hsieh,  M. Koenig, G. Korkmaz and F. Vega Redondo, "*Endogenous Riot Networks*." ([Slides with preliminary results](http://lachlandeer.github.io/files/riots_slides.pdf))

**L. Deer**, "*Trendy Topics: The Evolution of Research Topics and Methods in Leading Economics Journals.*"

**L. Deer**, "*Quantifying Product Buzz*."

<!-- **L. Deer** and P. Schmidt, "*Swipe Right for an STI? Tinder and the increase STIs in the United States*." -->

<!-- **L. Deer** and F. Vieder, "*Behaviourally Accurate Measures of Loss Aversion*." -->

<!-- R-C. Bayer and **L. Deer**, "*Consumption and Asset Trading Behaviour in a Dynamic Experimental Economy*." -->

<!-- **L. Deer** and C. Oertel, "*Nested Logit Demand Estimation with Aggregate Market Shares in `R`*." (`R` package)

**L. Deer** and C. Oertel, "*Merger Simulation in `R`*." (`R` package) -->


## WORKING PAPERS
G.S. Crawford, **L. Deer**, J. Smith and P. Sturgeon, 2017, "[*The Regulation of Public Service Broadcasters: Should there be more advertising on television?*](http://www.econ.uzh.ch/static/wp/econwp268.pdf)," CEPR Discussion Paper 12428 (Revise and Resubmit at IJIO).

R. Bouchouicha, **L. Deer**, A. Eid, P. McGee, D. Schoch and H. Stojic, Y. Ygosse-Battisti and F. Vieider, 2018, "[*Gender Effects and Loss Aversion: Yes, No, Maybe?*](http://lachlandeer.github.io/files/11_loss_aversion_gender.pdf)," Working Paper (Revise and Resubmit at Journal of Risk & Uncertainty).

## PUBLICATION
**L. Deer** and R-C. Bayer, 2016, "[*Pledges of Commitment and Cooperation in Partnerships*](http://www.mdpi.com/2073-4336/7/1/4/pdf)," Games 7(1) Art. No. 4.


# ACADEMIC PRESENTATIONS

*2019*: EMAC, Marketing Dynamics, Marketing Science.

*2018*: U Adelaide, Bocconi, Swiss IO Day, Marketing Science, EEA-ESEM, EARIE, Mallen20.

*2017*: UCSD Rady Marketing Lunch.

*2016*: Econometric Society - Australasian Meeting, Australian Conference of Economists.

*2015*: Zurich Workshop in Economics, ESA European Meeting.

*2012*: Econometric Society - Australasian Meeting.

*2011*: Econometric Society - Australasian Meeting, Australian Conference of Economists, Australia and New Zealand Workshop on Experimental Economics.

# AWARDS & RESEARCH GRANTS

## EXTERNAL
SNF Early PostDoc.Mobility Grant (Host Institute - Chicago Booth School of Business). \hfill 07/2019 - 12/2020

SNF Doc.Mobility Grant (Host Institution - Stanford GSB). \hfill 09/2016 - 05/2017

Econometric Society Travel Grant. \hfill 2012

Australian Postgraduate Award. \hfill 2010-2012

## INTERNAL
Dissertation Fellowship, University of Zurich. \hfill 2018-2019

Department Scholarship for PhD Students, University of Zurich. \hfill 2013-2018

Excellence in Masters Thesis Research, University of Adelaide. \hfill 2012

Certificate of Teaching Excellence, University of Adelaide. \hfill 2010

Legg Mason Asset Management Scholarship, University of Adelaide. \hfill 2008

School of Economics Merit List, University of Adelaide. \hfill 2005-2007

Summer Research Scholarship, University of Adelaide. \hfill 2006


# TEACHING EXPERIENCE
*Instructor, University of Zurich* \hfill 2016-2019

> Programming Practices for Research in Economics: Foundations (4 day intensive course, Winter 2019).

> Programming Practices for Research in Economics (3 week intensive course, Summer 2016 & Summer 2017).

*Instructor, Software Carpentry and Data Carpentry* \hfill 2016-2019

> 2-day programming workshops at U Zurich (February 2019), University of Trento (November 2018), University of Geneva (March 2018), Karolinska Institute  (October 2017), Stanford (June 2017), Federal Reserve Board of Governors (May 2017) and Federal Reserve in Kansas City (Feb 2017).

*Teaching Assistant, University of Zurich* \hfill 2014-2019

> Cross Section and Panel Data Econometrics (×2), Empirical Analysis of Asymmetric Information in Banking and Insurance Markets.

> Thesis Supervision: 8 $\times$ Bachelor's Theses, 4 $\times$ Master's Theses.


*Teaching Assistant, School of Economics, University of Adelaide* \hfill 2008-2012

> Business and Economic Statistics (×2), Intermediate Mathematical Economics, Intermediate Microeconomics (×4), International Financial Institutions and Markets, Macroeconomic Theory and Policy, Managerial Economics (×2), Money Banking and Financial Markets, Public Finance, Principles of Economics (×2), Principles of Macroeconomics (×2), Principles of Microeconomics I.

*Instructor, School of Economics, University of Adelaide* \hfill 2010

> Principles of Macroeconomics (Summer).

*Instructor, Bradford College, University of Adelaide* \hfill 2008 & 2010

> International Financial Institutions and Markets, Principles of Macroeconomics.

*Teaching Assistant, Flinders Business School, Flinders University* \hfill 2008

> Principles of Macroeconomics.

# PROFESSIONAL ACTIVITIES

*Ad-hoc Refereeing*

> Games, Information Economics and Policy, Journal of Economic Psychology, Journal of Economics and Statistics.

*Workshops and Working Groups Organized*

> Zurich Empirical Industrial Organization Group (2017, 2018, Lead Organizer), PhD Breakfast (2017, 2018, co-organized), Computational Economics Working Group (2016, 2018, co-organized), Zurich Workshop in Economics (2015, Lead Organizer).

*Community Engagement*

> Lesson Maintainer for Data Carpentry - Introduction to R for Geospatial Data

> Lesson Contributions to Software Carpentry and Data Carpentry:
    Data Organization in Spreadsheets for Social Scientists,
    Data Cleaning with OpenRefine for Social Scientists,
    Introduction to Geospatial Data with R,
    Data Analysis and Visualization in R (Ecology),
    Data Management with SQL for Ecologists,
    R for Reproducible Scientific Analysis.

# REFERENCES

Professor Gregory S. Crawford \hfill Professor Pradeep K. Chintagunta

Chair of Applied Microeconomics \hfill Joseph T. and Bernice S. Lewis Distinguished

Department of Economics, \hfill Service Professor of Marketing,

University of Zurich  \hfill Booth School of Business

gregory.crawford@econ.uzh.ch \hfill University of Chicago

+41 44 634 37 99 \hfill pradeep.chintagunta@chicagobooth.edu

\hfill +1-773-702-8015

\vfill

Professor Martin Natter \hfill Assist. Prof. Damian Kozbur

Chair of Marketing \hfill Assistant Professor

Department of Business Administration \hfill Department of Economics

Univeristy of Zurich \hfill University of Zurich

martin.natter@business.uzh.ch \hfill damian.kozbur@econ.uzh.ch

+41 44 634 29 62 \hfill +41 44 634 55 65

\newpage

# RESEARCH ABSTRACTS

## JOB MARKET PAPER

[*Online Word of Mouth and the Performance of New Products*](http://lachlandeer.github.io/files/deer_jmp.pdf)

*Abstract*:
We investigate the effects of online word of mouth on the demand for new products using Twitter data.
Twitter can both generate buzz & awareness as well as provide information on product quality that can readily diffuse through the population.
Leveraging comprehensive data from the US movie industry and Twitter, we estimate a structural model of consumer demand for attending theatrical releases in 2014-2015 that incorporates both information channels.
The results show that both channels are important, but differ across types of movies.
We find pre-release tweet volume is the most important channel for large franchise movies, generating buzz that influences box office earnings on the opening weekend.
Demand for mid tier movies responds to increasing awareness driven by the volume of tweets posted after a movie is released.
In contrast, the sentiment expressed in online WoM after a movie’s release influences box office demand in subsequent weekends for smaller movies.

## IN PROGRESS

*How does Advertising Influence Online Word of Mouth? Evidence from Twitter* ([Slides with preliminary results](http://lachlandeer.github.io/files/ads_wom_slides.pdf))

*Abstract*:
This paper investigates whether firms' advertising influences online consumer word of mouth in new product markets.
The increasing importance of online WoM in consumer decision making paired with the rise of 'second screening' by consumers means that firms are increasingly seeking to understanding how TV advertising impacts online behaviour.
We utilize a large, granular data set on minute-by-minute tweeting behaviour for all wide release movies in the United States over 2014/2015 and match it with data on individual ad insertions on national television to study whether TV ads lead to short-run spikes in online WoM.
Our econometric approach utilizes a high dimensional fixed effects strategy to control for the quantity of consumer tweets that are not driven by advertising.
Preliminary results show that TV ads cause short term increases in online WoM with an extra TV ad leading to 3.5 extra tweets, the equivalent of 1.5 additional minutes of tweeting in minutes where there is no TV advertising.
We also show that the effect of ads on tweeting only exists pre-release, and is larger the further away an ad is from the release date.

*Endogenous Riot Networks* ([Slides with preliminary results](http://lachlandeer.github.io/files/riots_slides.pdf))

*Abstract*:
We analyze binary choice models in communication networks, in which both, the formation of links in the network as well as the action choices are endogenous.
In particular we study the situation where an individual's payoffs are influenced by their own ideology, decisions of peers and beliefs about the actions of the entire population.
We provide a complete characterization of  the equilibrium action choices and networks, where agents choose their strategies - actions and links - according to a perturbed best response update rule.
We show that a threshold exists in the linking cost and the conformity parameter, giving rise to either a sparse or a densely connected communication network.
Moreover, we show how the theoretical model can be efficiently estimated using data on agents choices and their network of interactions.
We then structurally estimate the model using datasets of Twitter users that allows us to construct their social networks during the popular uprisings in Latin America and the Arab Spring.
Preliminary results emphasize the importance of the actions made by both peers (local effects) and the wider network (global effects).

*Trendy Topics: The Evolution of Research Topics and Methods in Leading Economics Journals*

*Abstract*:
This study investigates the content of the published scientific literature in the economics journals over 2000 to 2017.
I collect published journal abstracts from 30 of the leading economics journals.
I develop a Structural Topic Model to reveal the temporal dynamics of published papers across journals.
Preliminary results show that topics initially penetrate “top 5” journals before being picked up by field journals.
The analysis also reveals the specificities of each journal and identifies groups of journals with similar content – the results of which are not always consistent with prevailing wisdom.
The results provide an objective view of the published literature and are of interest to authors, editors, journals and publishers.

\newpage

*Quantifying Product Buzz*

*Abstract*:
Building product buzz, defined as emotion, energy, excitement, or anticipation expressed by consumers about a product, has become an essential part of modern marketing practice surrounding the launch of new products.
Despite its' perceived importance there is limited work that has tried to quantify product buzz around a product's impending release.
This paper develops a machine learning algorithm to quantify product buzz and track its evolution over time using social media data about new release movies from Twitter.
The proposed algorithm proceeds in three steps:
First, the algorithm classifies a tweet into one of three categories, consumer buzz, consumer review or firm generated content, based on a tweet's text and author.
Second, the text of tweets that are classified as consumer buzz is analysed to measure emotion and anticipation.
Third, the algorithm combines the volume of tweets, the emotions expressed within them and their dynamic properties to compute a measure of product buzz that evolves over time.
The results are among the first to provide a quantitative assessment of product buzz using the volume and constent of social media data and are of interest to marketing managers and academic researchers.

## WORKING PAPERS
[*The Regulation of Public Service Broadcasters: Should there be more advertising on television?*](http://www.econ.uzh.ch/static/wp/econwp268.pdf)

*Abstract*:
Increased competition for viewers’ time is threatening the viability of public-service broadcasters (PSBs) around the world.
Changing regulations regarding advertising minutes might increase revenues, but little is known about the structure of advertising demand.
To address this problem, we collect a unique dataset on monthly impacts (quantities) and prices of UK television channels between 2002 and 2009 to estimate the (inverse) demand for advertising on both public and commercial broadcasters.
We find that increasing PSB advertising minutes to the level permitted for non-PSBs would increase PSB and industry revenue by 10.5% and 6.7%.

[*Gender Effects and Loss Aversion: Yes, No, Maybe?*](http://lachlandeer.github.io/files/11_loss_aversion_gender.pdf)

 *Abstract*:
 Gender effects in risk taking have attracted much attention by economists, and remain debated.
 Loss aversion — the stylized finding that a given loss carries substantially greater weight for decisions than a monetarily equivalent gain — is a fundamental driver of risk aversion.
 We deploy four definitions of loss aversion commonly used in the literature to investigate gender effects.
 Even though the definitions only differ in subtle ways, we find women to be more loss averse than men according to one definition, while another definition results in no gender differences, and the remaining two definitions point to women being less loss averse than men.
 Conceptually, these contradictory effects can be organized by systematic measurement error resulting from model mis-specifications relative to the true underlying decision process.

## PUBLICATION
[*Pledges of Commitment and Cooperation in Partnerships*](http://www.mdpi.com/2073-4336/7/1/4/pdf)

*Abstract*: We use experimental methods to investigate whether pledges of commitment can improve cooperation in endogenously formed partnerships facing a social dilemma.
Treatments vary in terms of the individual’s:
    (1) opportunity to commit to their partner;
    (2) the cost of dissolving committed partnerships; and
    (3) the distribution of these dissolution costs between partners.
Our findings show that pledges of commitment alone can increase cooperation and welfare in committed partnerships.
The introduction of relatively large and equally split costs yields similar gains.
In contrast, when costs to dissolve committed partnerships fall solely on the individual choosing to break up, pledges of commitment fail to improve cooperation and welfare

\newpage

# PHD COURSEWORK

## COURSEWORK AT UNIVERSITY OF ZURICH

Microeconomics for Research Students I \hfill F. Kubler

Microeconomics for Research Students II \hfill C. Ewerhart

Econometrics for Research Students I \hfill M. Wolff

Econometrics for Research Students II \hfill R. Winkelmann

Macroeconomics for Research Students I \hfill F. Zilibotti & C. Winter

Macroeconomics for Research Students II \hfill C. Winter, M.Rendall & F. Brutti

Empirical Industrial Organization \hfill M. Sovinsky

Structural Econometrics for Applied Microeconomics \hfill G. Crawford

Computational Economics (ETH Zurich) \hfill D. Harenberg

Effective Programming Practices for Economists \hfill H.M. von Gaudecker

## COURSES AUDITED

Industrial Organization I (Stanford Econ) \hfill B. Larsen & L. Einav

Industrial Organization IIA (Stanford Econ) \hfill B. Larsen & M. Gentzkow

Bayesian Inference: Methods & Applications (Stanford GSB) \hfill S. Naranyan

Quantitative Methods for Empirical Research (Stanford GSB) \hfill G. Imbens

Statistical Learning Theory (ETH Zurich, Computer Science) \hfill J.M. Buhmann

## SHORT COURSES & SUMMER SCHOOLS

Markets with Asymmetric Information (Tinbergen Institute) \hfill L. Einav & J. Levin

Barcelona GSE Summer School in Microeconometrics (BGSE) \hfill B. Baltagi, S. Litschig & S. Jiménez-Martín

Zurich Initiative For Computational Economics (U Zurich Business) \hfill K. Judd, C.L. Su, H. Paarsch

Structural Econometrics and Market Responses in Imperfectly Competitive Industries (CEMFI) \hfill A. Pakes

The Econometrics of Models with Simultaneous Interactions: Theory and Applications to IO (CEMFI) \hfill E.Tamer

Panel Data Econometrics (CEMFI) \hfill J. Wooldridge

Causality & Machine Learning (UCL) \hfill S. Athey & G. Imbens

Machine Learning for Treatment Effects and Structural Equation Models  (UCL) \hfill V. Chernozhukov

Empirical Models of Differentiated Products (UCL) \hfill S. Berry

Dynamic Programming Theory, Computation and Empirical Applications  (UCL) \hfill J. Rust, F. Ishakov, B. Scherning

Applied Nonparametric Econometrics  (UCL) \hfill J. Racine

Fixed Effects Treatment of Panel Data  (UCL) \hfill B. Honore
